# Generated by Django 3.2.22 on 2023-11-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_auto_20231112_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='duedate',
        ),
    ]
