# Generated by Django 3.2.22 on 2023-11-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_remove_todomodel_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todomodel',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
